"""remove amt column

Revision ID: b03c0097e3c1
Revises: 2d5fe0c938c8
Create Date: 2024-02-07 13:23:40.607040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b03c0097e3c1'
down_revision = '2d5fe0c938c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('amt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amt', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
