"""change type to Numeric

Revision ID: d26177f059a1
Revises: 454b89f92cf8
Create Date: 2024-02-07 15:50:07.235159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd26177f059a1'
down_revision = '454b89f92cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
