"""change type to float

Revision ID: f5bffa1d444e
Revises: d26177f059a1
Create Date: 2024-02-07 16:04:01.961195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5bffa1d444e'
down_revision = 'd26177f059a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)

    # ### end Alembic commands ###
